### PR TITLE
Fix libfrida installation on Android from APK and improvement #2

### PR DESCRIPTION
**Pull request by eclipse95**
Hi,
This PR provides improvement related to the issue #2.

In my cases, the libfrida file wasn't copy in the app's lib folder (`/data/data/<app>/lib/`).
In the APK file, the libfrida file was in `lib/` instead of `lib/<arch>/`.
The second commit fixes this issue.

### CODE REVIEW

**Review by dan1t0 — COMMENTED** [review]
done! thanks

**Comment by eclipse95** [comment]
Hi,
If you think that the PR is OK to merge, please merge the PR to your master branch.

**Comment by dan1t0** [comment]
add my changes and I will accept getfridalibs.sh :-)

cheers!!! and thanks

**Comment by eclipse95** [comment]
Hi,
The PR includes all my commits and yours on the branch ``master`` of my fork.

**Review by dan1t0 — APPROVED** [review]

**Review by dan1t0 — CHANGES_REQUESTED** [review]
accept this pls

**Review by dan1t0 — APPROVED** [review]

**Review by dan1t0 — COMMENTED** [review]
not works

**Review by dan1t0 — APPROVED** [review]
thanks!

**Pull request merged**
